### ISSUE TITLE
The `--version` flag is passed to nvim, so it is not a way to figure out version of neoray

### ISSUE THREAD

**Issue by bunyk** [hismailbulut/neoray#15]
- Operating System or distro: Ubuntu
 - neoray version: master branch for today, hard to figure out :)

**Describe the bug**
`--version` flag is passed to nvim, it  probably prints version to stdout and exits, but neoray still tries to establish rpc session with it. 

I would expect it to output version of `nvim`.

**Steps to reproduce**

Just start it with `--version` and observe error logs:

```
tbunyk@ZALANDO-33620:~/projects/neoray$ bin/neoray_debug --version
[DEBUG] [NVIM] Neovim started with command: nvim --embed --version
[ERROR] [NVIM] Failed to get api information: msgpack/rpc: session closed
[ERROR] [NVIM] Failed to set client information: msgpack/rpc: session closed
[ERROR] [NVIM] Failed to execute scripts.vim: msgpack/rpc: session closed
[FATAL] [NVIM] Attaching ui failed: msgpack/rpc: session closed
```

**Comment by hismailbulut** [comment]
Ok I accept. I did it like this because I am using windows and gui programs in windows prints it like this. Printing both messagebox and stdout may good but in linux only stdout will be usefull and in windows only messagebox. Maybe --version only prints the version and exits, on linux only to stdout and on windows only to messagebox. I dont know what will be good on macos.

**Comment by bunyk** [comment]
:+1:
